# Generated by Django 4.2.2 on 2023-08-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auctions.category'),
        ),
    ]
