# Generated by Django 4.2.2 on 2023-08-25 16:02

from django.db import migrations, models
import django.db.models.deletion

def get_default_category(apps, schema_editor):
    Category = apps.get_model('auctions', 'Category')  # Update app name
    return Category.objects.get(name='Other').pk


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category.py'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='category',
            field=models.ForeignKey(
                default=get_default_category,
                on_delete=models.PROTECT,
                to='auctions.Category'
            ),
        ),
    ]