# Generated by Django 4.2.2 on 2023-09-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
