# Generated by Django 4.2.2 on 2023-09-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_listings_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('Win', 'Won'), ('Lost', 'Lost'), ('winning', 'Winning'), ('Losing', 'Losing')], max_length=10),
        ),
    ]
